(function(c,r,w){function m(a,b,d){e("SUBSCRIBE",a,b,function(a){a.body.ok?d(a.body.data):d(null)})}function e(a,b,d,g){if("http"===n.substring(0,4))t(a,b,d,g);else if("ws"===n.substring(0,2))u(a,b,d,g);else throw"SIB Server is not a valid DWR or WebSocket endpoint";}function p(a,b,d,g){k.push({tipoQuery:a,query:b,cipherMessage:d,responseCallback:g});1==k.length&&(b=k[0].query,k[0].cipherMessage&&(b="JOIN"==a?c.kpName.length+"#"+c.kpName+Base64.encode(XXTEA.encrypt(b,c.cipherKey),!1):Base64.encode(XXTEA.encrypt(b,
c.cipherKey))),l.send(b))}function u(a,b,d,g){if("WebSocket"in window)null==l?(l=new WebSocket(n),l.onopen=function(){p(a,b,d,g)},l.onmessage=function(a){a=a.data.trim();if(""!=a){mensajeSSAP=null;clearMsg=a;try{mensajeSSAP=c.parsearMensajeSSAP(a),mensajeSSAP.messageType}catch(v){clearMsg=XXTEA.decrypt(Base64.decode(a),c.cipherKey),mensajeSSAP=c.parsearMensajeSSAP(clearMsg)}if("INDICATION"!=mensajeSSAP.messageType){a=mensajeSSAP;var b=k[0];"JOIN"==a.messageType&&null!=a.body.data&&1==a.body.ok&&(f=
a.sessionKey);b.responseCallback(a);k.shift();0<k.length&&(a=k[0].query,k[0].cipherMessage&&(a="JOIN"==k[0].tipoQuery?c.kpName.length+"#"+c.kpName+Base64.encode(XXTEA.encrypt(a,c.cipherKey),!1):Base64.encode(XXTEA.encrypt(a,c.cipherKey))),l.send(a))}else try{indicationForSubscription&&indicationForSubscription(clearMsg)}catch(v){}}},l.onclose=function(){}):p(a,b,d,g);else throw"Your Browser does not support WebSocket";}function t(a,b,d,g){var h=null;GatewayDWR._path=n;d&&(b="JOIN"==a?c.kpName.length+
"#"+c.kpName+Base64.encode(XXTEA.encrypt(b,c.cipherKey),!1):Base64.encode(XXTEA.encrypt(b,c.cipherKey)));GatewayDWR.process(b,function(b){d&&(b=XXTEA.decrypt(Base64.decode(b),c.cipherKey));h="INSERT"==a||"UPDATE"==a||"DELETE"==a?c.parsearMensajeSSAP(b):c.parsearMensajeSSAP(c.validarSSAPConDataString(b));if(null!=h&&null!=h.body.data&&1==h.body.ok)switch(a){case "JOIN":f=h.sessionKey;g(h);break;case "LEAVE":f=null;g(h);break;case "INSERT":g(h);break;case "QUERY":g(h);break;case "SUBSCRIBE":g(h);break;
default:g(h)}else g(h)})}function q(a){0!=a.indexOf("{")&&(a="{"+a+"}");return a}var f=null,n=null,l=null;try{pathToWebsocketServer&&(n=pathToWebsocketServer)}catch(a){}try{pathToDwrServlet&&(n=pathToDwrServlet+"/")}catch(a){}c.cipherKey=null;c.kpName=null;c.join=function(a,b,d,g){e("JOIN",'{"body":{"instance":"'+d+'","password":"'+b+'","user":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":null}',!1,g)};c.joinRenovateSessionKey=function(a,b,d,g){e("JOIN",'{"body":{"instance":"'+
d+'","password":"'+b+'","user":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":"'+f+'"}',!1,g)};c.joinCipher=function(a,b,d,g){e("JOIN",'{"body":{"instance":"'+d+'","password":"'+b+'","user":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":null}',!0,g)};c.joinRenovateSessionCipher=function(a,b,d,g){e("JOIN",'{"body":{"instance":"'+d+'","password":"'+b+'","user":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":"'+f+'"}',!0,g)};c.joinToken=function(a,
b,d){e("JOIN",'{"body":{"instance":"'+b+'","token":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":null}',!1,d)};c.joinTokenRenovateSession=function(a,b,d){e("JOIN",'{"body":{"instance":"'+b+'","token":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":"'+f+'"}',!1,d)};c.joinTokenCipher=function(a,b,d){e("JOIN",'{"body":{"instance":"'+b+'","token":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":null}',!0,d)};c.joinTokenRenovateSessionCipher=function(a,
b,d){e("JOIN",'{"body":{"instance":"'+b+'","token":"'+a+'"},"direction":"REQUEST","messageType":"JOIN","sessionKey":"'+f+'"}',!0,d)};c.leave=function(a){e("LEAVE",'{"body":{},"direction":"REQUEST","messageType":"LEAVE","sessionKey":"'+f+'"}',!1,a)};c.leaveCipher=function(a){e("LEAVE",'{"body":{},"direction":"REQUEST","messageType":"LEAVE","sessionKey":"'+f+'"}',!0,a)};c.insert=function(a,b,d){a=q(a);a=a.replace(/'/g,'"');e("INSERT",'{"body":{"data":'+a+',"query":null},"direction":"REQUEST","messageType":"INSERT","ontology":"'+
b+'","sessionKey":"'+f+'"}',!1,d)};c.insertWithQueryType=function(a,b,d,g){e("INSERT","NATIVE"==d?'{"body":{"data":'+a+',"query":null,"queryType":"'+d+'"},"direction":"REQUEST","messageType":"INSERT","ontology":"'+b+'","sessionKey":"'+f+'"}':'{"body":{"query":"'+a+'","data":null,"queryType":"'+d+'"},"direction":"REQUEST","messageType":"INSERT","ontology":"'+b+'","sessionKey":"'+f+'"}',!1,g)};c.insertCipher=function(a,b,d){a=q(a);a=a.replace(/'/g,'"');e("INSERT",'{"body":{"data":'+a+',"query":null},"direction":"REQUEST","messageType":"INSERT","ontology":"'+
b+'","sessionKey":"'+f+'"}',!0,d)};c.insertWithQueryTypeCipher=function(a,b,d,g){e("INSERT","NATIVE"==d?'{"body":{"data":'+a+',"query":null,"queryType":"'+d+'"},"direction":"REQUEST","messageType":"INSERT","ontology":"'+b+'","sessionKey":"'+f+'"}':'{"body":{"query":"'+a+'","data":null,"queryType":"'+d+'"},"direction":"REQUEST","messageType":"INSERT","ontology":"'+b+'","sessionKey":"'+f+'"}',!0,g)};c.update=function(a,b,d,g){e("UPDATE",'{"body":{"data":"'+a+'","query":"'+b+'"},"direction":"REQUEST","messageType":"UPDATE","ontology":"'+
d+'","sessionKey":"'+f+'"}',!1,g)};c.updateWithQueryType=function(a,b,d,g,c){e("UPDATE",'{"body":{"data":"'+a+'","query":"'+b+'","queryType":"'+g+'"},"direction":"REQUEST","messageType":"UPDATE","ontology":"'+d+'","sessionKey":"'+f+'"}',!1,c)};c.updateCipher=function(a,b,d,g){e("UPDATE",'{"body":{"data":"'+a+'","query":"'+b+'"},"direction":"REQUEST","messageType":"UPDATE","ontology":"'+d+'","sessionKey":"'+f+'"}',!0,g)};c.updateWithQueryTypeCipher=function(a,b,d,g,c){e("UPDATE",'{"body":{"data":"'+
a+'","query":"'+b+'","queryType":"'+g+'"},"direction":"REQUEST","messageType":"UPDATE","ontology":"'+d+'","sessionKey":"'+f+'"}',!0,c)};c.remove=function(a,b,d){e("DELETE",'{"body":{"data":null,"query":"'+a+'"},"direction":"REQUEST","messageType":"DELETE","ontology":"'+b+'","sessionKey":"'+f+'"}',!1,d)};c.removeWithQueryType=function(a,b,d,c){e("DELETE",'{"body":{"data":null,"query":"'+a+'","queryType":"'+d+'"},"direction":"REQUEST","messageType":"DELETE","ontology":"'+b+'","sessionKey":"'+f+'"}',
!1,c)};c.removeCipher=function(a,b,d){e("DELETE",'{"body":{"data":null,"query":"'+a+'"},"direction":"REQUEST","messageType":"DELETE","ontology":"'+b+'","sessionKey":"'+f+'"}',!1,d)};c.removeWithQueryTypeCipher=function(a,b,d,c){e("DELETE",'{"body":{"data":null,"query":"'+a+'","queryType":"'+d+'"},"direction":"REQUEST","messageType":"DELETE","ontology":"'+b+'","sessionKey":"'+f+'"}',!1,c)};c.query=function(a,b,d){e("QUERY",'{"body":{"query":"'+a+'"},"direction":"REQUEST","ontology":"'+b+'","messageType":"QUERY","sessionKey":"'+
f+'"}',!1,d)};c.queryWithQueryType=function(a,b,d,c,h){null!=b&&(b='"'+b+'"');a=null==c?'{"body":{"query":"'+a+'","queryType":"'+d+'","queryParams": null},"direction":"REQUEST","ontology":'+b+',"messageType":"QUERY","sessionKey":"'+f+'"}':'{"body":{"query":"'+a+'","queryType":"'+d+'","queryParams":'+JSON.stringify(c)+'},"direction":"REQUEST","ontology":'+b+',"messageType":"QUERY","sessionKey":"'+f+'"}';e("QUERY",a,!1,h)};c.queryCipher=function(a,b,d){e("QUERY",'{"body":{"query":"'+a+'"},"direction":"REQUEST","ontology":"'+
b+'","messageType":"QUERY","sessionKey":"'+f+'"}',!0,d)};c.queryWithQueryTypeCipher=function(a,b,d,c,h){null!=b&&(b='"'+b+'"');a=null==c?'{"body":{"query":"'+a+'","queryType":"'+d+'","queryParams": null},"direction":"REQUEST","ontology":'+b+',"messageType":"QUERY","sessionKey":"'+f+'"}':'{"body":{"query":"'+a+'","queryType":"'+d+'","queryParams":'+JSON.stringify(c)+'},"direction":"REQUEST","ontology":'+b+',"messageType":"QUERY","sessionKey":"'+f+'"}';e("QUERY",a,!0,h)};c.subscribe=function(a,b,d,
c){m('{"body":{"query":"'+a+'","msRefresh":"'+d+'"},"direction":"REQUEST","ontology":"'+b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}',!1,c)};c.subscribeWithQueryType=function(a,b,d,c,e){m('{"body":{"query":"'+a+'","msRefresh":"'+c+'","queryType":"'+d+'"},"direction":"REQUEST","ontology":"'+b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}',!1,e)};c.subscribeWithQueryTypeSibDefinedParams=function(a,b,d,c,e,k){a=null==c?'{"body":{"query":"'+a+'","msRefresh":"'+e+'","queryType":"'+d+'"},"direction":"REQUEST","ontology":"'+
b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}':'{"body":{"query":"'+a+'","msRefresh":"'+e+'","queryType":"'+d+'","queryParams":'+JSON.stringify(c)+'},"direction":"REQUEST","ontology":"'+b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}';m(a,!1,k)};c.subscribeCipher=function(a,b,d,c){m('{"body":{"query":"'+a+'","msRefresh":"'+d+'"},"direction":"REQUEST","ontology":"'+b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}',!0,c)};c.subscribeWithQueryTypeSibDefinedParamsCipher=function(a,b,d,
c,e,k){a=null==c?'{"body":{"query":"'+a+'","msRefresh":"'+e+'","queryType":"'+d+'"},"direction":"REQUEST","ontology":"'+b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}':'{"body":{"query":"'+a+'","msRefresh":"'+e+'","queryType":"'+d+'","queryParams":'+JSON.stringify(c)+'},"direction":"REQUEST","ontology":"'+b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}';m(a,!0,k)};c.subscribeWithQueryTypeCipher=function(a,b,c,g,e){m('{"body":{"query":"'+a+'","msRefresh":"'+g+'","queryType":"'+c+'"},"direction":"REQUEST","ontology":"'+
b+'","messageType":"SUBSCRIBE","sessionKey":"'+f+'"}',!0,e)};c.unsubscribe=function(a,b,c){null!=a?e("UNSUBSCRIBE",'{"body":{"idSuscripcion":"'+a+'"},"direction":"REQUEST","messageType":"UNSUBSCRIBE","sessionKey":"'+f+'"}',!1,function(a){b(a)}):c("ERROR_1")};c.unsubscribeCipher=function(a,b,c){null!=a?e("UNSUBSCRIBE",'{"body":{"idSuscripcion":"'+a+'"},"direction":"REQUEST","messageType":"UNSUBSCRIBE","sessionKey":"'+f+'"}',!0,function(a){b(a)}):c("ERROR_1")};var k=[];c.parsearMensajeSSAP=function(a){try{return r.parseJSON(a.replace(/'/g,
'\\"'))}catch(b){return null}};c.validarSSAPConDataString=function(a){return a.replace(/(body|data)\"\s*:\s*\"({|\[)/g,'$1":$2').replace(/(}|])\"\s*,\s*\"(direction|ontology|message|session|error|ok)/g,'$1,"$2').replace(/\\+\"/g,'"')};c.validarSSAP=function(a){return a.replace(/\\+\"/g,'"').replace(/(body|data)\"\s*:\s*\"({|\[)/g,'$1":$2').replace(/(}|])\"\s*,\s*\"(direction|ontology|message|session|error|ok)/g,'$1,"$2')};c.escapeJSONObject=function(a){return a.replace(/\"/g,'\\"').replace(/\\\\\"/g,
'\\\\\\"')}})(window.sofia2=window.sofia2||{},jQuery);