"undefined"==typeof dwr&&(dwr={});dwr.util||(dwr.util={});dwr.util._escapeHtml=!0;dwr.util.setEscapeHtml=function(a){dwr.util._escapeHtml=a};dwr.util._shouldEscapeHtml=function(a){return a&&null!=a.escapeHtml?a.escapeHtml:dwr.util._escapeHtml};dwr.util.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};
dwr.util.unescapeHtml=function(a){return a.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#039;/g,"'").replace(/&amp;/g,"&")};dwr.util.replaceXmlCharacters=function(a){a=a.replace("&","+");a=a.replace("<","\u2039");a=a.replace(">","\u203a");a=a.replace("'","\u2018");return a=a.replace('"',"\u201c")};dwr.util.containsXssRiskyCharacters=function(a){return-1!=a.indexOf("&")||-1!=a.indexOf("<")||-1!=a.indexOf(">")||-1!=a.indexOf("'")||-1!=a.indexOf('"')};
dwr.util.onReturn=function(a,b){a||(a=window.event);a&&a.keyCode&&13==a.keyCode&&b()};dwr.util.selectRange=function(a,b,d){a=dwr.util._getElementById(a,"selectRange()");if(null!=a){if(a.setSelectionRange)a.setSelectionRange(b,d);else if(a.createTextRange){var c=a.createTextRange();c.moveStart("character",b);c.moveEnd("character",d-a.value.length);c.select()}a.focus()}};
dwr.util.byId=function(){for(var a=[],b=0;b<arguments.length;b++){var d=arguments[b],c;if("string"==typeof d){if(c=document.getElementById(d),document.all&&c&&dwr.util._getId(c)!=d){c=null;var e=document.all[d];e.tagName&&(e=[e]);for(var f=0;f<e.length;f++)if(dwr.util._getId(e[f])==d){c=e[f];break}}}else c=d;if(1==arguments.length)return c;a.push(c)}return a};dwr.util._getId=function(a){var b=a.getAttribute("id");dwr.util._isObject(b)&&(b=a.attributes.id.value);return b};
"undefined"==typeof $&&($=dwr.util.byId);
dwr.util.toDescriptiveString=function(a,b,d){function c(a,b,d,f){var g="";try{if(dwr.util._isString(a)){0==b&&a.length>f.shortStringMaxLength&&(a=a.substring(0,f.shortStringMaxLength-3)+"...");if(f.escapeHtml){for(var k=a.split("\n"),l=0;l<k.length;l++)k[l]=dwr.util.escapeHtml(k[l]);a=k.join("\n")}a=0==b?a.replace(/\n|\r|\t/g,function(a){switch(a){case "\n":return"\\n";case "\r":return"";case "\t":return"\\t"}}):a.replace(/\n|\r|\t/g,function(a){switch(a){case "\n":return f.lineTerminator+e(d+1,f);
case "\r":return"";case "\t":return"\\t"}});g='"'+a+'"'}else if(dwr.util._isFunction(a))g="function";else if(dwr.util._isArrayLike(a))if(0==b)g=0<a.length?"[...]":"[]";else{var h=[];h.push("[");for(var m=0,l=0;l<a.length;l++)if(l in a||"[object NodeList]"==a){var u=a[l];0<m&&h.push(", ");if(1==b){if(m==f.oneLineMaxItems){h.push("...");break}}else h.push(f.lineTerminator+e(d+1,f));l!=m&&(h.push(l),h.push(":"));h.push(c(u,b-1,d+1,f));m++}1<b&&h.push(f.lineTerminator+e(d,f));h.push("]");g=h.join("")}else if(dwr.util._isObject(a)&&
!dwr.util._isDate(a))if(0==b)g=dwr.util._detailedTypeOf(a);else{h=[];"Object"!=dwr.util._detailedTypeOf(a)&&(h.push(dwr.util._detailedTypeOf(a)),"object"!=typeof a.valueOf()&&(h.push(":"),h.push(c(a.valueOf(),1,d,f))),h.push(" "));h.push("{");var t=dwr.util._isHTMLElement(a),m=0,n;for(n in a){var r=a[n];if(t){if(null==r)continue;if("function"==typeof r)continue;if(p[n])continue;if(n.toUpperCase()==n)continue}0<m&&h.push(", ");if(1==b){if(m==f.oneLineMaxItems){h.push("...");break}}else h.push(f.lineTerminator+
e(d+1,f));h.push(n.length>f.propertyNameMaxLength?n.substring(0,f.propertyNameMaxLength-3)+"...":n);h.push(":");h.push(c(r,b-1,d+1,f));m++}1<b&&0<m&&h.push(f.lineTerminator+e(d,f));h.push("}");g=h.join("")}else g=""+a;return g}catch(q){return q.message?q.message:""+q}}function e(a,b){var c=[];c.push(b.baseIndent);for(var d=0;d<a;d++)c.push(b.childIndent);return c.join("")}void 0===b&&(b=1);var f={};dwr.util._isObject(d)&&(f=d);d={escapeHtml:!1,baseIndent:"",childIndent:"\u00a0\u00a0",lineTerminator:"\n",
oneLineMaxItems:5,shortStringMaxLength:13,propertyNameMaxLength:30};for(var g in d)g in f||(f[g]=d[g]);var p={document:!0,ownerDocument:!0,all:!0,parentElement:!0,parentNode:!0,offsetParent:!0,children:!0,firstChild:!0,lastChild:!0,previousSibling:!0,nextSibling:!0,innerHTML:!0,outerHTML:!0,innerText:!0,outerText:!0,textContent:!0,attributes:!0,style:!0,currentStyle:!0,runtimeStyle:!0,parentTextEdit:!0};return c(a,b,0,f)};
dwr.util.useLoadingMessage=function(a){var b;b=a?a:"Loading";dwr.engine.setPreHook(function(){var a=dwr.util.byId("disabledZone");if(a)dwr.util.byId("messageZone").innerHTML=b,a.style.visibility="visible",dwr.util._disabledZoneUseCount++,dwr.util.byId("messageZone").style.visibility="visible";else{a=document.createElement("div");a.setAttribute("id","disabledZone");a.style.position="absolute";a.style.zIndex="1000";a.style.left="0px";a.style.top="0px";a.style.width="100%";a.style.height="100%";window.ActiveXObject&&
(a.style.background="white",a.style.filter="alpha(opacity=0)");document.body.appendChild(a);a=document.createElement("div");a.setAttribute("id","messageZone");a.style.position="absolute";a.style.top="0px";a.style.right="0px";a.style.background="red";a.style.color="white";a.style.fontFamily="Arial,Helvetica,sans-serif";a.style.padding="4px";document.body.appendChild(a);var c=document.createTextNode(b);a.appendChild(c);dwr.util._disabledZoneUseCount=1}});dwr.engine.setPostHook(function(){dwr.util._disabledZoneUseCount--;
0==dwr.util._disabledZoneUseCount&&(dwr.util.byId("disabledZone").style.visibility="hidden",dwr.util.byId("messageZone").style.visibility="hidden")})};dwr.util.setHighlightHandler=function(a){dwr.util._highlightHandler=a};dwr.util.yellowFadeHighlightHandler=function(a){dwr.util._yellowFadeProcess(a,0)};dwr.util._yellowFadeSteps="d0 b0 a0 90 98 a0 a8 b0 b8 c0 c8 d0 d8 e0 e8 f0 f8".split(" ");
dwr.util._yellowFadeProcess=function(a,b){a=dwr.util.byId(a);b<dwr.util._yellowFadeSteps.length?(a.style.backgroundColor="#ffff"+dwr.util._yellowFadeSteps[b],setTimeout("dwr.util._yellowFadeProcess('"+dwr.util._getId(a)+"',"+(b+1)+")",200)):a.style.backgroundColor="transparent"};dwr.util.borderFadeHighlightHandler=function(a){a.style.borderWidth="2px";a.style.borderStyle="solid";dwr.util._borderFadeProcess(a,0)};dwr.util._borderFadeSteps="d0 b0 a0 90 98 a0 a8 b0 b8 c0 c8 d0 d8 e0 e8 f0 f8".split(" ");
dwr.util._borderFadeProcess=function(a,b){a=dwr.util.byId(a);b<dwr.util._borderFadeSteps.length?(a.style.borderColor="#ff"+dwr.util._borderFadeSteps[b]+dwr.util._borderFadeSteps[b],setTimeout("dwr.util._borderFadeProcess('"+dwr.util._getId(a)+"',"+(b+1)+")",200)):a.style.backgroundColor="transparent"};dwr.util.focusHighlightHandler=function(a){try{a.focus()}catch(b){}};dwr.util._highlightHandler=null;
dwr.util.highlight=function(a,b){b&&b.highlightHandler?b.highlightHandler(dwr.util.byId(a)):null!=dwr.util._highlightHandler&&dwr.util._highlightHandler(dwr.util.byId(a))};
dwr.util.setValue=function(a,b,d){null==b&&(b="");null==d&&(d={});var c=a;a=dwr.util.byId(a);var e=null;null==a&&(e=document.getElementsByName(c),1<=e.length&&(a=e.item(0)));if(null==a)dwr.util._debug("setValue() can't find an element with id/name: "+c+".");else if(dwr.util.highlight(a,d),dwr.util._isHTMLElement(a,"select"))"select-multiple"==a.type&&dwr.util._isArray(b)?dwr.util._selectListItems(a,b):dwr.util._selectListItem(a,b);else if(dwr.util._isHTMLElement(a,"input"))if("radio"==a.type||"checkbox"==
a.type)if(e&&1<=e.length)for(d=0;d<e.length;d++){if(c=e.item(d),c.type==a.type)if(dwr.util._isArray(b)){c.checked=!1;for(var f=0;f<b.length;f++)b[f]==c.value&&(c.checked=!0)}else c.checked=c.value==b}else a.checked=1==b;else a.value=b;else dwr.util._isHTMLElement(a,"textarea")?a.value=b:dwr.util._isHTMLElement(a,"img")?a.src=b:b.nodeType?(9==b.nodeType&&(b=b.documentElement),b=dwr.util._importNode(a.ownerDocument,b,!0),a.appendChild(b)):dwr.util._shouldEscapeHtml(d)?"textContent"in a?a.textContent=
b.toString():"innerText"in a?a.innerText=b.toString():a.innerHTML=dwr.util.escapeHtml(b.toString()):a.innerHTML=b};dwr.util._selectListItems=function(a,b){var d=0,c,e;for(c=0;c<a.options.length;c++)for(a.options[c].selected=!1,e=0;e<b.length;e++)a.options[c].value==b[e]&&(a.options[c].selected=!0,d++);if(d!=b.length)for(c=0;c<a.options.length;c++)for(e=0;e<b.length;e++)a.options[c].text==b[e]&&(a.options[c].selected=!0)};
dwr.util._selectListItem=function(a,b){var d=!1,c;for(c=0;c<a.options.length;c++)a.options[c].value==b?d=a.options[c].selected=!0:a.options[c].selected=!1;if(!d)for(c=0;c<a.options.length;c++)a.options[c].selected=a.options[c].text==b};
dwr.util.getValue=function(a,b){null==b&&(b={});var d=a;a=dwr.util.byId(a);var c=null;null==a&&(c=document.getElementsByName(d),1<=c.length&&(a=c.item(0)));if(null==a)return dwr.util._debug("getValue() can't find an element with id/name: "+d+"."),"";if(dwr.util._isHTMLElement(a,"select")){if("select-multiple"==a.type){for(var d=[],e=0;e<a.options.length;e++)if(c=a.options[e],c.selected){var f=c.getAttributeNode("value");f&&f.specified?d.push(c.value):d.push(c.text)}return d}d=a.selectedIndex;return-1!=
d?(c=a.options[d],(f=c.getAttributeNode("value"))&&f.specified?c.value:c.text):""}if(dwr.util._isHTMLElement(a,"input")){if("radio"==a.type){if(c&&1<=c.length)for(e=0;e<c.length;e++)if(f=c.item(e),f.type==a.type&&f.checked)return f.value;return a.checked}if("checkbox"==a.type){if(c&&1<=c.length){d=[];for(e=0;e<c.length;e++)f=c.item(e),f.type==a.type&&f.checked&&d.push(f.value);return d}return a.checked}return"file"==a.type?a:a.value}if(dwr.util._isHTMLElement(a,"textarea"))return a.value;if(dwr.util._shouldEscapeHtml(b)){if("textContent"in
a)return a.textContent;if("innerText"in a)return a.innerText}return a.innerHTML};dwr.util.getText=function(a){a=dwr.util._getElementById(a,"getText()");if(null==a)return null;if(!dwr.util._isHTMLElement(a,"select"))return dwr.util._debug("getText() can only be used with select elements. Attempt to use: "+dwr.util._detailedTypeOf(a)+" from  id: "+orig+"."),"";var b=a.selectedIndex;return-1!=b?a.options[b].text:""};
dwr.util.setValues=function(a,b){var d="",c=100;b&&"prefix"in b&&(d=b.prefix);b&&"idPrefix"in b&&(d=b.idPrefix);b&&"depth"in b&&(c=b.depth);dwr.util._setValuesRecursive(a,d,c,b)};
dwr.util._setValuesRecursive=function(a,b,d,c){if(0!=d)if(dwr.util._isArray(a)&&0<a.length&&dwr.util._isObject(a[0]))for(var e=0;e<a.length;e++)dwr.util._setValuesRecursive(a[e],b+"["+e+"]",d-1,c);else if(dwr.util._isObject(a)&&!dwr.util._isArray(a))for(e in a){var f=b?b+"."+e:e;dwr.util._isObject(a[e])&&!dwr.util._isArray(a[e])&&!dwr.util._isDate(a[e])||dwr.util._isArray(a[e])&&0<a[e].length&&dwr.util._isObject(a[e][0])?dwr.util._setValuesRecursive(a[e],f,d-1,c):"function"!=typeof a[e]&&(null!=dwr.util.byId(f)||
1<=document.getElementsByName(f).length)&&dwr.util.setValue(f,a[e],c)}};dwr.util.getValues=function(a,b){if("string"==typeof a||dwr.util._isHTMLElement(a))return dwr.util.getFormValues(a);var d="",c=100;null!=b&&"prefix"in b&&(d=b.prefix);null!=b&&"idPrefix"in b&&(d=b.idPrefix);null!=b&&"depth"in b&&(c=b.depth);dwr.util._getValuesRecursive(a,d,c,b);return a};
dwr.util.getFormValues=function(a){var b=null;"string"==typeof a?(b=document.forms[a],null==b&&(b=dwr.util.byId(a))):dwr.util._isHTMLElement(a)&&(b=a);if(null!=b){if(null==b.elements)return alert("getFormValues() requires an object or reference to a form element."),null;a={};for(var d,c,e=0;e<b.elements.length;e++)b[e].type in{button:0,submit:0,reset:0,image:0,file:0}||(b[e].name?(d=b[e].name,c=dwr.util.getValue(d)):(d=b[e].id?b[e].id:"element"+e,c=dwr.util.getValue(b[e])),a[d]=c);return a}};
dwr.util._getValuesRecursive=function(a,b,d,c){if(0!=d)if(dwr.util._isArray(a)&&0<a.length&&dwr.util._isObject(a[0]))for(var e=0;e<a.length;e++)dwr.util._getValuesRecursive(a[e],b+"["+e+"]",d-1,c);else if(dwr.util._isObject(a)&&!dwr.util._isArray(a))for(e in a){var f=b?b+"."+e:e;dwr.util._isObject(a[e])&&!dwr.util._isArray(a[e])||dwr.util._isArray(a[e])&&0<a[e].length&&dwr.util._isObject(a[e][0])?dwr.util._getValuesRecursive(a[e],f,d-1,c):"function"!=typeof a[e]&&(null!=dwr.util.byId(f)||1<=document.getElementsByName(f).length)&&
(a[e]=dwr.util.getValue(f))}};
dwr.util.addOptions=function(a,b){a=dwr.util._getElementById(a,"addOptions()");if(null!=a){var d=dwr.util._isHTMLElement(a,"select"),c=dwr.util._isHTMLElement(a,["ul","ol"]);if(!d&&!c)dwr.util._debug("addOptions() can only be used with select/ul/ol elements. Attempt to use: "+dwr.util._detailedTypeOf(a));else if(null!=b){var e=arguments.length,f={},g=arguments[e-1];2<e&&dwr.util._isObject(g)&&(f=g,e--);g=null;3<=e&&(g=arguments[2]);var p=null;4<=e&&(p=arguments[3]);!f.optionCreator&&d&&(f.optionCreator=
dwr.util._defaultOptionCreator);!f.optionCreator&&c&&(f.optionCreator=dwr.util._defaultListItemCreator);f.document=a.ownerDocument;if(dwr.util._isArray(b))for(var k=0;k<b.length;k++)if(f.data=b[k],f.text=null,f.value=null,d){if(null!=g?null!=p?(f.text=dwr.util._getValueFrom(b[k],p),f.value=dwr.util._getValueFrom(b[k],g)):f.text=f.value=dwr.util._getValueFrom(b[k],g):f.text=f.value=dwr.util._getValueFrom(b[k]),null!=f.text||f.value)c=f.optionCreator(f),c.text=f.text,c.value=f.value,a.options[a.options.length]=
c}else f.value=dwr.util._getValueFrom(b[k],g),null!=f.value&&(c=f.optionCreator(f),dwr.util._shouldEscapeHtml(f)&&(f.value=dwr.util.escapeHtml(f.value)),c.innerHTML=f.value,a.appendChild(c));else if(null!=p){if(!d){alert("dwr.util.addOptions can only create select lists from objects.");return}for(k in b)if(f.data=b[k],f.value=dwr.util._getValueFrom(b[k],g),f.text=dwr.util._getValueFrom(b[k],p),null!=f.text||f.value)c=f.optionCreator(f),c.text=f.text,c.value=f.value,a.options[a.options.length]=c}else{if(!d){dwr.util._debug("dwr.util.addOptions can only create select lists from objects.");
return}for(k in b)"function"!=typeof b[k]&&(f.data=b[k],null==g?(f.value=k,f.text=b[k]):(f.value=b[k],f.text=k),null!=f.text||f.value)&&(c=f.optionCreator(f),c.text=f.text,c.value=f.value,a.options[a.options.length]=c)}dwr.util.highlight(a,f)}}};dwr.util._getValueFrom=function(a,b){return null==b?a:"function"==typeof b?b(a):a[b]};dwr.util._defaultOptionCreator=function(a){return a.document.createElement("option")};dwr.util._defaultListItemCreator=function(a){return a.document.createElement("li")};
dwr.util.removeAllOptions=function(a){a=dwr.util._getElementById(a,"removeAllOptions()");if(null!=a){var b=dwr.util._isHTMLElement(a,"select"),d=dwr.util._isHTMLElement(a,["ul","ol"]);if(b||d)if(b)a.options.length=0;else for(;0<a.childNodes.length;)a.removeChild(a.firstChild);else dwr.util._debug("removeAllOptions() can only be used with select, ol and ul elements. Attempt to use: "+dwr.util._detailedTypeOf(a))}};
dwr.util.addRows=function(a,b,d,c){a=dwr.util._getElementById(a,"addRows()");if(null!=a)if(dwr.util._isHTMLElement(a,["table","tbody","thead","tfoot"])){c||(c={});c.rowCreator||(c.rowCreator=dwr.util._defaultRowCreator);c.cellCreator||(c.cellCreator=dwr.util._defaultCellCreator);c.document=a.ownerDocument;var e,f;if(dwr.util._isArray(b))for(f=0;f<b.length;f++)c.rowData=b[f],c.rowIndex=f,c.rowNum=f,c.data=null,c.cellNum=-1,e=dwr.util._addRowInner(d,c),null!=e&&a.appendChild(e);else if("object"==typeof b){f=
0;for(var g in b)c.rowData=b[g],c.rowIndex=g,c.rowNum=f,c.data=null,c.cellNum=-1,e=dwr.util._addRowInner(d,c),null!=e&&a.appendChild(e),f++}dwr.util.highlight(a,c)}else dwr.util._debug("addRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(a))};dwr.util._emptyTableCellReplacement="<div style='width:0;height:0;overflow:hidden;'></div>";
dwr.util._addRowInner=function(a,b){var d=b.rowCreator(b);if(null==d)return null;for(var c=0;c<a.length;c++){var e=a[c];b.data="function"==typeof e?e(b.rowData,b):e||"";b.cellNum=c;e=b.cellCreator(b);null!=e&&("data"in b?dwr.util._isHTMLElement(b.data)?e.appendChild(b.data):dwr.util._shouldEscapeHtml(b)&&"string"==typeof b.data?e.innerHTML=dwr.util.escapeHtml(b.data):e.innerHTML=b.data:e.innerHTML=dwr.util._emptyTableCellReplacement,d.appendChild(e))}return d};dwr.util._defaultRowCreator=function(a){return a.document.createElement("tr")};
dwr.util._defaultCellCreator=function(a){return a.document.createElement("td")};dwr.util.removeAllRows=function(a,b){a=dwr.util._getElementById(a,"removeAllRows()");if(null!=a)if(b||(b={}),b.filter||(b.filter=function(){return!0}),dwr.util._isHTMLElement(a,["table","tbody","thead","tfoot"]))for(var d=a.firstChild,c;null!=d;)c=d.nextSibling,b.filter(d)&&a.removeChild(d),d=c;else dwr.util._debug("removeAllRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(a))};
dwr.util.setClassName=function(a,b){a=dwr.util._getElementById(a,"setClassName()");null!=a&&(a.className=b)};dwr.util.addClassName=function(a,b){a=dwr.util._getElementById(a,"addClassName()");null!=a&&(a.className+=" "+b)};dwr.util.removeClassName=function(a,b){a=dwr.util._getElementById(a,"removeClassName()");null!=a&&(a.className=a.className.replace(new RegExp("(^|\\s)"+b+"(\\s|$)","g"),""))};
dwr.util.toggleClassName=function(a,b){a=dwr.util._getElementById(a,"toggleClassName()");if(null!=a){var d=new RegExp("(^|\\s)"+b+"(\\s|$)");d.test(a.className)?a.className=a.className.replace(d,""):a.className+=" "+b}};dwr.util.cloneNode=function(a,b){a=dwr.util._getElementById(a,"cloneNode()");if(null==a)return null;null==b&&(b={});var d=a.cloneNode(!0);"idPrefix"in b||"idSuffix"in b?dwr.util._updateIds(d,b):dwr.util._removeIds(d);a.parentNode.insertBefore(d,a);return d};
dwr.util._updateIds=function(a,b){null==b&&(b={});dwr.util._getId(a)&&a.setAttribute("id",("idPrefix"in b?b.idPrefix:"")+dwr.util._getId(a)+("idSuffix"in b?b.idSuffix:""));for(var d=a.childNodes,c=0;c<d.length;c++){var e=d.item(c);1==e.nodeType&&dwr.util._updateIds(e,b)}};dwr.util._removeIds=function(a){dwr.util._getId(a)&&a.removeAttribute("id");a=a.childNodes;for(var b=0;b<a.length;b++){var d=a.item(b);1==d.nodeType&&dwr.util._removeIds(d)}};
dwr.util.cloneNodeForValues=function(a,b,d){a=dwr.util._getElementById(a,"cloneNodeForValues()");if(null==a)return null;null==d&&(d={});var c;c=null!=d.idPrefix?d.idPrefix:dwr.util._getId(a)||"";return dwr.util._cloneNodeForValuesRecursive(a,b,c,d)};
dwr.util._cloneNodeForValuesRecursive=function(a,b,d,c){if(dwr.util._isArray(b)){for(var e=[],f=0;f<b.length;f++){var g=dwr.util._cloneNodeForValuesRecursive(a,b[f],d+"["+f+"]",c);e.push(g)}return e}if(dwr.util._isObject(b)&&!dwr.util._isArray(b)){g=a.cloneNode(!0);if(c.updateCloneStyle&&g.style)for(e in c.updateCloneStyle)g.style[e]=c.updateCloneStyle[e];dwr.util._replaceIds(g,dwr.util._getId(a),d);a.parentNode.insertBefore(g,a);dwr.util._cloneSubArrays(b,d,c);return g}return null};
dwr.util._replaceIds=function(a,b,d){var c=dwr.util._getId(a);if(c){var e=null;if(c==b)e=d;else if(c.length>b.length&&c.substr(0,b.length)==b){var f=c.charAt(b.length);if("."==f||"["==f)e=d+c.substr(b.length)}e?a.setAttribute("id",e):a.removeAttribute("id")}a=a.childNodes;for(c=0;c<a.length;c++)e=a.item(c),1==e.nodeType&&dwr.util._replaceIds(e,b,d)};
dwr.util._cloneSubArrays=function(a,b,d){for(prop in a){var c=a[prop];if(dwr.util._isArray(c)){if(0<c.length&&dwr.util._isObject(c[0])){var e=b+"."+prop,f=dwr.util.byId(e);null!=f&&dwr.util._cloneNodeForValuesRecursive(f,c,e,d)}}else dwr.util._isObject(c)&&dwr.util._cloneSubArrays(c,b+"."+prop,d)}};dwr.util._getElementById=function(a,b){var d=a;a=dwr.util.byId(a);null==a&&dwr.util._debug(b+" can't find an element with id: "+d+".");return a};
dwr.util._isHTMLElement=function(a,b){if(null==a||"object"!=typeof a||null==a.nodeName)return!1;if(null!=b){var d=a.nodeName.toLowerCase();if("string"==typeof b)return d==b.toLowerCase();if(dwr.util._isArray(b)){for(var c=!1,e=0;e<b.length&&!c;e++)d==b[e].toLowerCase()&&(c=!0);return c}dwr.util._debug("dwr.util._isHTMLElement was passed test node name that is neither a string or array of strings");return!1}return!0};
dwr.util._detailedTypeOf=function(a){var b=typeof a;"object"==b&&(b=Object.prototype.toString.apply(a),b=b.substring(8,b.length-1));return b};dwr.util._isObject=function(a){return a&&"object"==typeof a};dwr.util._isArray=function(a){return a&&"[object Array]"==Object.prototype.toString.call(a)};
dwr.util._isArrayLike=function(a){return a&&"number"==typeof a.length&&(a.propertyIsEnumerable&&0==a.propertyIsEnumerable("length")||!a.constructor||"[object Object]"!=a)&&!dwr.util._isString(a)&&!dwr.util._isFunction(a)&&!a.tagName};dwr.util._isString=function(a){return a&&("string"==typeof a||"[object String]"==Object.prototype.toString.call(a))};dwr.util._isFunction=function(a){return a&&("function"==typeof a||"[object Function]"==Object.prototype.toString.call(a))&&"[object NodeList]"!=a};
dwr.util._isDate=function(a){return a&&"[object Date]"==Object.prototype.toString.call(a)};
dwr.util._importNode=function(a,b,d){var c;if(1==b.nodeType){c=a.createElement(b.nodeName);for(var e=0;e<b.attributes.length;e++){var f=b.attributes[e];null!=f.nodeValue&&""!=f.nodeValue&&c.setAttribute(f.name,f.nodeValue)}null!=b.style&&(c.style.cssText=b.style.cssText)}else 3==b.nodeType&&(c=a.createTextNode(b.nodeValue));if(d&&b.hasChildNodes())for(e=0;e<b.childNodes.length;e++)c.appendChild(dwr.util._importNode(a,b.childNodes[e],!0));return c};
dwr.util._debug=function(a,b){var d=!1;try{window.console?(b&&window.console.trace&&window.console.trace(),window.console.log(a),d=!0):window.opera&&window.opera.postError&&(window.opera.postError(a),d=!0)}catch(e){}if(!d&&(d=document.getElementById("dwr-debug"))){var c=a+"<br/>"+d.innerHTML;2048<c.length&&(c=c.substring(0,2048));d.innerHTML=c}};